import { Card } from "../../components/ui/card";

const insights = [
  {
    title: "Clip curation",
    body: "CLIP + Whisper identified 18 segments with >125% retention rate across TikTok and Reels.",
  },
  {
    title: "Caption intelligence",
    body: "GPT prompt stack deployed for Galaxy Launch: tone matched to Gen-Z tech influencers with bilingual variants.",
  },
  {
    title: "Fraud signals",
    body: "ClickHouse anomaly model flagged inconsistent IP clusters in Malaysia – auto-escalated to admin review.",
  },
];

const trendTable = [
  { tag: "#GalaxyLaunch", lift: "+284%", platform: "TikTok" },
  { tag: "#ZeroLagChallenge", lift: "+132%", platform: "Instagram Reels" },
  { tag: "#Nightography", lift: "+88%", platform: "YouTube Shorts" },
];

export default function AIInsightsPage() {
  return (
    <div className="space-y-8">
      <header>
        <h2 className="text-2xl font-semibold text-white">AI Insights & Automation</h2>
        <p className="text-sm text-slate-400">
          Summaries, highlights, and fraud scoring generated by the MVPX AI stack.
        </p>
      </header>

      <section className="grid gap-4 md:grid-cols-3">
        {insights.map((insight) => (
          <Card
            key={insight.title}
            title={insight.title}
            className="border border-white/10 bg-gradient-to-br from-ink-800 to-ink-900"
          >
            <p className="text-sm text-slate-200">{insight.body}</p>
          </Card>
        ))}
      </section>

      <Card title="Trending intelligence" className="border border-white/10">
        <div className="overflow-hidden rounded-2xl border border-white/5">
          <table className="min-w-full divide-y divide-white/5 text-sm text-slate-200">
            <thead className="bg-surface-200/60 text-left text-xs uppercase tracking-[0.4em] text-slate-400">
              <tr>
                <th className="px-6 py-3 font-semibold">Hashtag</th>
                <th className="px-6 py-3 font-semibold">Lift</th>
                <th className="px-6 py-3 font-semibold">Platform</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {trendTable.map((trend) => (
                <tr key={trend.tag}>
                  <td className="px-6 py-3 font-semibold text-white">{trend.tag}</td>
                  <td className="px-6 py-3 text-accent-400">{trend.lift}</td>
                  <td className="px-6 py-3 text-slate-300">{trend.platform}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      <Card title="Highlight generator" className="border border-white/10">
        <div className="grid gap-4 lg:grid-cols-3">
          {["15 sec", "30 sec", "60 sec"].map((duration) => (
            <div
              key={duration}
              className="rounded-2xl border border-white/5 bg-ink-900/50 p-4 text-sm text-slate-200"
            >
              <p className="text-xs uppercase tracking-[0.3em] text-slate-400">
                {duration}
              </p>
              <h3 className="mt-2 text-lg font-semibold text-white">
                Highlight package
              </h3>
              <p className="mt-2 text-xs text-slate-400">
                Auto-captioned vertical cut, burned-in CTA, explicit compliance check.
              </p>
              <button
                type="button"
                className="mt-4 inline-flex w-full items-center justify-center rounded-xl border border-accent-500/40 bg-accent-500/10 px-4 py-2 text-xs font-semibold uppercase tracking-wide text-accent-400"
              >
                Generate preview
              </button>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}
